services:
  craftiquebe.api:
    image: ${DOCKER_REGISTRY-}craftiquebeapi
    container_name: craftique-api
    build:
      context: .
      dockerfile: CraftiqueBE.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStringsDefaultConnection=Server=sqlserver-container-craftique,1433;Database=CraftiqueDB;User Id=sa;Password=YourStrongP@ssword;TrustServerCertificate=True;
      # JWT Settings
      - JWTAccessTokenExpiredByMinutes=15
      - JWTRefreshTokenExpiredByHours=3
      - JWTAudience=CraftiqueClient
      - JWTIssuer=CraftiqueAPI
      - JWTSecretKey=ThisIsTheSecureKeyByKien1234567890
      # Google Authentication
      - AuthenticationGoogleClientId=622721304691-32fun7k34v8uu58d3c68a5amu3fkb4ik.apps.googleusercontent.com
      - AuthenticationGoogleClientSecret=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
      # Mail Settings
      - MailSettingsDefaultSender=craftique68@gmail.com
      - MailSettingsPassword=swggrulwsdywcbhq
      - MailSettingsDisplayName=Craftique Shop
      - MailSettingsProvider=smtp.gmail.com
      - MailSettingsPort=587
      # PayOS Settings
      - PayOSClientId=46c1b4f5-0ddd-4573-9602-ecbf8e5e47d6
      - PayOSApiKey=9c88eb58-63ab-4100-880c-7d65ae6466c6
      - PayOSChecksumKey=71df19c1b9a85693b537cefc0de193ef50bb32815d90685fa4d1b47d97efad12
      - PayOSReturnUrl=http://localhost:3000/payment-callback
      - PayOSCancelUrl=http://localhost:3000/purchase-order
    depends_on:
      - sql-server
    networks:
      - craftique-network
    restart: on-failure
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container-craftique
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongP@ssword
    ports:
      - "1434:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - craftique-network
volumes:
  mssqldata:
networks:
  craftique-network: